#ifndef DIMSCREEN_H_INCLUDED
#define DIMSCREEN_H_INCLUDED

#define BLOCK_SIZE 32 /// Heigh = Width
#define NB_OF_CASE_WIDTH 16
#define NB_OF_CASE_HEIGHT 12
#define SCREEN_WIDTH NB_OF_CASE_WIDTH * BLOCK_SIZE
#define SCREEN_HEIGHT NB_OF_CASE_HEIGHT * BLOCK_SIZE

#endif // DIMSCREEN_H_INCLUDED
